export const WIDGET_POSITION_CHANGE = 'CANVAS/WIDGET_POSITION_CHANGE';
export const WIDGET_SIZE_CHANGE = 'CANVAS/WIDGET_SIZE_CHANGE';
export const WIDGET_ADD = 'CANVAS/WIDGET_ADD';
export const WIDGET_REMOVE = 'CANVAS/WIDGET_REMOVE';
export const WIDGET_MOVE_UP = 'CANVAS/WIDGET_MOVE_UP';
export const WIDGET_MOVE_DOWN = 'CANVAS/WIDGET_MOVE_DOWN';
export const WIDGET_SET_PROPERTIES = 'CANVAS/WIDGET_SET_PROPERTIES';

export const CANVAS_SELECT_WIDGET = 'CANVAS/SELECT_WIDGET';
export const CANVAS_OPEN_DOCUMENT = 'CANVAS/CANVAS_OPEN_DOCUMENT';
export const CANVAS_SAVE_DOCUMENT = 'CANVAS/CANVAS_SAVE_DOCUMENT';
